### ISSUE TITLE
Vite 3.1

### ISSUE THREAD

**Issue by X7Becka** [Menci/vite-plugin-top-level-await#8] opened 2022-09-19 22:40 UTC
Hello! After update vite to 3.1 plugin stops working.

**Comment by Menci** [comment] 2022-09-21 15:15
Reproduce?

**Comment by X7Becka** [comment] 2022-09-22 05:17
No link to reproduce. Internal product. Just stops working on any config.

**Comment by Menci** [comment] 2022-09-22 05:30
Closing since no reproduce.

**Closed by Menci** 2022-09-22 05:30 UTC
