### ISSUE TITLE
has error like this ,when i build

### ISSUE THREAD

**Issue by jzfai** [Menci/vite-plugin-top-level-await#1] opened 2022-03-10 08:25 UTC
![image](https://user-images.githubusercontent.com/35098590/157619379-147da778-d934-4a80-aa92-82d8185e689a.png)

**Comment by Menci** [comment] 2022-03-10 10:04
Could you please make a minimal reproduce and post as attachment?

**Comment by linkurzweg** [comment] 2022-03-23 11:03
@Menci Looks like this is a problem related to Windows. Building the project on my Mac works just fine, but my Colleague who uses Windows gets the same error message and it also fails with the same error when deploying on Azure DevOps.

**Comment by Menci** [comment] 2022-03-23 11:13
How did you use this plugin and top-level await code? Could you give me a minimal reproduce project?

**Comment by Menci** [comment] 2022-03-23 11:13
I'll try to allocate a Windows VM to investigate and fix this ...

**Comment by linkurzweg** [comment] 2022-03-23 11:18
> How did you use this plugin and top-level await code? Could you give me a minimal reproduce project?

I use it in a Vue 3 project for a composable that has to do with authentication. I'll try to setup a minimal project on GitHub and have my Colleague test it, then I'll send you the link.

**Comment by linkurzweg** [comment] 2022-03-23 12:19
@Menci minimal example here: https://github.com/linkurzweg/vite-top-level-await-example
As before, builds fine on MacOS but the build fails on Windows.

**Comment by Timehello** [comment] 2022-03-24 03:21
@Menci this issue may happen on windows os
![image](https://user-images.githubusercontent.com/7313124/159835298-345d7e94-9368-4c24-95cc-b795e8b6ca1c.png)
if add the replace function to transform the backslash of url to slash, the problem will not happen

**Comment by Menci** [comment] 2022-03-24 08:07
The fix https://github.com/Menci/vite-plugin-top-level-await/commit/107401ecd68bdb601d9705f08547682349565443#diff-79340eaedfdc61bf528bd1fc90b881aeeb52b9964736af508485ab5f0588ef60R1 is landed in `v0.0.4`. Could you please try it?

**Comment by linkurzweg** [comment] 2022-03-24 09:19
Can confirm it's fixed now. Thanks a lot!

**Closed** 2022-03-24 09:21 UTC
